export const environment = {
  production: ${production},
  stage: '${stage}',
  build: '${build}',
  resource_urls: {
    portal: '${portal_url}',
    portal_api: '${portal_api_url}',
    guacamole: '${guacamole_url}',
    sftp: '${sftp_url}',
    sub1: '${sub1_url}',
    sub2: '${sub2_url}',
  },

  // TODO -> Generated by Terraform, but values are hard coded to dev environment
  cognito: {
    Auth: {
      Cognito: {
        userPoolId: "us-east-1_sNIwupW53",
        userPoolClientId: "6s90hhstst6td8sdo1ntl3laet",
        loginWith: {
          oauth: {
            domain: "ecs-dev-sdc-dot-webportal.auth.us-east-1.amazoncognito.com",
            scopes: ["email", "profile", "openid"],
            redirectSignIn: [window.location.origin + "/dashboard"],
            redirectSignOut: [window.location.origin + '/index.html'],
            responseType: "token",
          }
        }
      }
    }
  }
};
